export const LIKE_SUCCESS = "LIKE_SUCCESS";
export const LIKE_FAIL = "LIKE_FAIL";
export const LIKE_REQUEST = "LIKE_REQUEST";

export const COMMENT_SUCCESS = "COMMENT_SUCCESS";
export const COMMENT_FAIL = "COMMENT_FAIL";
export const COMMENT_REQUEST = "COMMENT_REQUEST";

export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";
export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";

export const ADD_TO_FAVOURITES_SUCCESS = "ADD_TO_FAVOURITES_SUCCESS";
export const ADD_TO_FAVOURITES_FAIL = "ADD_TO_FAVOURITES_FAIL";
export const ADD_TO_FAVOURITES_REQUEST = "ADD_TO_FAVOURITES_REQUEST";

export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";
export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";

export const ClearErrors = "ClearErrors";
export const ClearMessages = "ClearMessages";
